[project]
name = "library-catalog"
version = "0.1.0"
description = "The backend service for Library catalog"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "alembic>=1.17.1",
    "asyncpg>=0.30.0",
    "dotenv>=0.9.9",
    "fastapi>=0.120.4",
    "greenlet>=3.1.1",
    "pydentic>=0.0.1.dev3",
    "sqlalchemy>=2.0.44",
    "uvicorn>=0.38.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
]
lint = [
    "ruff>=0.14.3",
]
test = [
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
]
