"""add_book_enrichment_fields

Revision ID: a7e8d67af3c8
Revises: f3fe7bd9c133
Create Date: 2025-11-02 16:21:56.442005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7e8d67af3c8'
down_revision: Union[str, Sequence[str], None] = 'f3fe7bd9c133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('cover_image_url', sa.String(), nullable=True))
    op.add_column('books', sa.Column('description', sa.String(), nullable=True))
    op.add_column('books', sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'rating')
    op.drop_column('books', 'description')
    op.drop_column('books', 'cover_image_url')
    # ### end Alembic commands ###
